
var libros = ["EPP,Susanne S. \"Discrete mathematics with applications\"",
"GRASSMAN,Winfried,TREMBLAY,Jean-Paul. \"Matemática discreta y lógica: Una perspectiva desde la Ciencia de la COmputación\"",
"JOHNSONBAUGH,Richard.\"Discrete Mathematics\"",
"KOLMAN,Bernard. \"Discrete Mathematical Structures\"",
"LIU,C.L. \"Elementos de matmaticas discretas\"",
"ROSEN,Kenneth. \"Matematicas discretas y sus aplicaciones.\"",
"TREMBLAY,Jean-Paul.\"Matematicas Discretas con aplicacion a las ciencias de la computacion\"",
"VEERARAJAN,t. \"Matematicas discretas con teoria de graficas y combinatoria\"",
"BALAKRISHNAN,V.K. \"Introductory Discrete Mathematics\"",
"COMELLAS,Francesc. \"Matematica Discreta\"",
"ESPINOSA,Ramon. \"Matematicas Discretas\"",
"LOVASZ,Laszlo. \"Discrete Mathematics: Elementary and Beyond\"",
"SCHEINERMAN,Edward. \"Matematicas Discretas\"",
"STEIN,Clifford.\"Discrete Mathematics for computer scientists.\""];

var ubicacion = ["Centro de Ciencias Geonómicas",
"No Disponible",
"Instituto de Fisica",
"Facultad de Estudios Superiores Aragón",
"Biblioteca Central,Facultad de Contaduria y Adminitracion, Facultad de Ingenieria: Posgrado",
"Facultad de Ciencias, Facultad de Ingenieria: Enrique Rivero Borell, Facultad de Estudios Superiores Cuatitulan 1",
"FES: Aragon, Facultad de COntaduria y Administracion, FES: Cuatitlan 1, Facultad de Ciencias, Facultad de Ingenieria, Facultad de Ingenieria: Enrique Rivero Borrell, Instituo de Investigaciones Economicas, Instituto de Matematicas.",
"FES Acatlan, Facultad de Ingenieria, Biblioteca Central, Facultad de Ciencias, FES Cuatitlan 1, Facultad de Ingenieria: Enrique Rivero Borrell.",
"Centro de Ciencias Geonómicas, Facultad de Ciencias, Instituto de Investigaciones en Materiales, Instituto de Matematicas, Centro de Ciencias Matematicas-Morelia,Facultad de Ingenieria: Enrique Rivero Borrell",
"Biblioteca Central, FES Cuatitlan 1, D.G.T.I.C Centro Nuevo Leon, Facultad de Ingenieria: Enrique Rivero Borrell",
"No Disponible",
"No Disponible",
"Biblioteca Central, FES Cuatitlan 1, CCH Plantel Vallejo, CCH Oriente, Facultad de Ingenieria: Posgrado, FES Zaragoza, Campo Dos, Facultad de Ingenieria: Enrique Rivero Borrell, CCH Sur, FES Acatlan.",
"Biblioteca Central, Facultad de Ingenieria."];

var clasificacion = ["QA39.2 E66 2011",
"No Disponible",
"QA39.2 J64 2009",
"QA76.9 K64 2009",
"QA 164 L5818",
"QA39.2 R6618 2004",
"QA39.2T44 1996",
"QA248 V4418",
"QA39.2 B356 1996",
"QA37.3 M3718 2002",
"No Disponible",
"No Disponible",
"QA37.2 S3518",
"QA76.9M35 S755"];

var libLinea = ["",
"http://www.mediafire.com/file/wbw2ehb6k43z6wf/2+Matematica_discreta_y_logica-W.K.Grassmann.rar",
"",
"",
"",
"",
"",
"",
"",
"",
"http://www.buscador.iumx.eu/leer-online/?t=matem%C3%A1tica+discreta+armenta+alfaomega+PDF&d=http%3A%2F%2Fwww.fi.unju.edu.ar%2Fimages%2Fprogramas%2F2015%2FMatematica_Discreta.pdf",
"http://www.pdfdrive.net/discrete-mathematics-elementary-and-beyond-e7607750.html",
""];